version: "3.9"
services:

    rclex_docker:
        image: rclex/rclex_docker:${TAG:-latest}
        volumes:
            - ../rclex:/root/rclex
            - .:/root/rclex_connection_tests/
        tty: true
